name: Github actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Make install dependencies
        run: make install

      - name: Run linter
        run: make lint
