name: Github actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here

      - name: Make install dependencies
        uses: make install

      - name: Run linter
        uses: make lint
